# Generated by Django 3.2.13 on 2022-07-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_auto_20220705_2101"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="tag",
            new_name="tags",
        ),
        migrations.RenameField(
            model_name="recipetag",
            old_name="tag",
            new_name="tags",
        ),
    ]
