# Generated by Django 3.2.13 on 2022-06-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220625_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag', to='recipes.tag', verbose_name='тэг'),
            preserve_default=False,
        ),
    ]
