# Generated by Django 3.2.13 on 2022-07-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingridients',
            old_name='quantity',
            new_name='amount',
        ),
    ]
