# Generated by Django 3.2.13 on 2022-07-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_auto_20220706_1707"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="recipe",
            new_name="recipes",
        ),
    ]
