# Generated by Django 3.2.13 on 2022-07-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_rename_recipe_favorite_recipes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favorite",
            name="recipe_in_favorite_unique",
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "recipes"), name="recipe_in_favorite_unique"
            ),
        ),
    ]
