# Generated by Django 3.2.13 on 2022-07-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipetag'),
    ]

    operations = [        

        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(related_name='recipe_tag', through='recipes.RecipeTag', to='recipes.Tag'),
        )
    ]
