# Generated by Django 3.2.13 on 2022-07-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20220703_1939'),
    ]

    operations = [        
        migrations.RemoveField(
                    model_name='recipe',
                    name='ingredients',
                ),

                migrations.AddField(
                    model_name='recipe',
                    name='ingredients',
                    field=models.ManyToManyField(related_name='recipe_ingredients', through='recipes.RecipeIngredients', to='recipes.Ingridients'),
                )
    ]
