# Generated by Django 3.2.13 on 2022-07-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20220713_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridients',
            new_name='Ingridient',
        ),
    ]
