# Generated by Django 3.2.13 on 2022-07-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredients',
            name='amount',
        ),
        migrations.AlterField(
            model_name='ingridients',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeIngredients', to='recipes.Ingridients'),
        ),
    ]
