# Generated by Django 3.2.13 on 2022-06-24 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимое имя пользователя', regex='^[-a-zA-Z0-9_]+$')]),
        ),
    ]
